/**
 * NEXA database schema.
 *
 * Conventions enforced across every table:
 *  - Primary keys are UUID v4 generated by the database (`gen_random_uuid()`).
 *  - Every business-owned row carries `business_id` with `ON DELETE CASCADE`.
 *    This column is the tenancy boundary; the API layer never issues a query
 *    against these tables without it (see apps/api/src/db/scope.ts).
 *  - Money is stored as an integer count of **minor units** (pesewas, cents…)
 *    in `bigint` columns. Floating point never touches a monetary value.
 *  - Every table carries `created_at`; mutable tables also carry `updated_at`.
 *  - Enumerations come from @nexa/types so the database and the application
 *    cannot drift apart.
 */
import { relations, sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';
import {
  ACTIVITY_SEVERITIES,
  ACTIVITY_SOURCES,
  AI_ACTION_STATUSES,
  AI_MESSAGE_ROLES,
  APPOINTMENT_STATUSES,
  CAMPAIGN_STATUSES,
  CUSTOMER_STATUSES,
  INVENTORY_MOVEMENT_REASONS,
  INVOICE_STATUSES,
  MEMBER_ROLES,
  NOTIFICATION_CHANNELS,
  ORDER_STATUSES,
  PAYMENT_METHODS,
  PAYMENT_STATUSES,
  PRODUCT_KINDS,
  SUBSCRIPTION_PLANS,
  SUBSCRIPTION_STATUSES,
  TASK_PRIORITIES,
  TASK_STATUSES,
} from '@nexa/types';

/* -------------------------------------------------------------------------- */
/* Enums                                                                       */
/* -------------------------------------------------------------------------- */

export const memberRoleEnum = pgEnum('member_role', MEMBER_ROLES);
export const customerStatusEnum = pgEnum('customer_status', CUSTOMER_STATUSES);
export const productKindEnum = pgEnum('product_kind', PRODUCT_KINDS);
export const orderStatusEnum = pgEnum('order_status', ORDER_STATUSES);
export const paymentStatusEnum = pgEnum('payment_status', PAYMENT_STATUSES);
export const paymentMethodEnum = pgEnum('payment_method', PAYMENT_METHODS);
export const invoiceStatusEnum = pgEnum('invoice_status', INVOICE_STATUSES);
export const taskStatusEnum = pgEnum('task_status', TASK_STATUSES);
export const taskPriorityEnum = pgEnum('task_priority', TASK_PRIORITIES);
export const appointmentStatusEnum = pgEnum('appointment_status', APPOINTMENT_STATUSES);
export const inventoryReasonEnum = pgEnum('inventory_reason', INVENTORY_MOVEMENT_REASONS);
export const activitySeverityEnum = pgEnum('activity_severity', ACTIVITY_SEVERITIES);
export const activitySourceEnum = pgEnum('activity_source', ACTIVITY_SOURCES);
export const aiActionStatusEnum = pgEnum('ai_action_status', AI_ACTION_STATUSES);
export const aiMessageRoleEnum = pgEnum('ai_message_role', AI_MESSAGE_ROLES);
export const subscriptionPlanEnum = pgEnum('subscription_plan', SUBSCRIPTION_PLANS);
export const subscriptionStatusEnum = pgEnum('subscription_status', SUBSCRIPTION_STATUSES);
export const notificationChannelEnum = pgEnum('notification_channel', NOTIFICATION_CHANNELS);
export const campaignStatusEnum = pgEnum('campaign_status', CAMPAIGN_STATUSES);

/* -------------------------------------------------------------------------- */
/* Column helpers                                                              */
/* -------------------------------------------------------------------------- */

const pk = () => uuid('id').primaryKey().default(sql`gen_random_uuid()`);
const createdAt = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const updatedAt = () => timestamp('updated_at', { withTimezone: true }).notNull().defaultNow();
/** Money in minor units. bigint keeps us safe past the 2.1bn integer ceiling. */
const moneyCol = (name: string) => bigint(name, { mode: 'number' }).notNull().default(0);

/* -------------------------------------------------------------------------- */
/* Identity                                                                    */
/* -------------------------------------------------------------------------- */

export const users = pgTable(
  'users',
  {
    id: pk(),
    email: varchar('email', { length: 254 }).notNull(),
    passwordHash: text('password_hash').notNull(),
    fullName: varchar('full_name', { length: 120 }).notNull(),
    avatarUrl: text('avatar_url'),
    phone: varchar('phone', { length: 40 }),
    timezone: varchar('timezone', { length: 60 }),
    emailVerifiedAt: timestamp('email_verified_at', { withTimezone: true }),
    lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
    failedLoginCount: integer('failed_login_count').notNull().default(0),
    lockedUntil: timestamp('locked_until', { withTimezone: true }),
    lastBusinessId: uuid('last_business_id'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex('users_email_unique').on(sql`lower(${t.email})`)],
);

export const sessions = pgTable(
  'sessions',
  {
    id: pk(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** SHA-256 of the opaque token. The raw token only ever lives in the cookie. */
    tokenHash: varchar('token_hash', { length: 64 }).notNull(),
    userAgent: text('user_agent'),
    ipAddress: varchar('ip_address', { length: 64 }),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(),
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex('sessions_token_hash_unique').on(t.tokenHash), index('sessions_user_idx').on(t.userId)],
);

export const verificationTokens = pgTable(
  'verification_tokens',
  {
    id: pk(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    purpose: varchar('purpose', { length: 40 }).notNull(), // 'email_verification' | 'password_reset'
    tokenHash: varchar('token_hash', { length: 64 }).notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    consumedAt: timestamp('consumed_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex('verification_tokens_hash_unique').on(t.tokenHash),
    index('verification_tokens_user_idx').on(t.userId, t.purpose),
  ],
);

/* -------------------------------------------------------------------------- */
/* Tenancy                                                                     */
/* -------------------------------------------------------------------------- */

export const businesses = pgTable(
  'businesses',
  {
    id: pk(),
    name: varchar('name', { length: 160 }).notNull(),
    slug: varchar('slug', { length: 180 }).notNull(),
    industry: varchar('industry', { length: 80 }).notNull().default('Other'),
    businessType: varchar('business_type', { length: 80 }),
    country: varchar('country', { length: 2 }).notNull().default('GH'),
    currency: varchar('currency', { length: 3 }).notNull().default('GHS'),
    locale: varchar('locale', { length: 12 }).notNull().default('en-GH'),
    timezone: varchar('timezone', { length: 60 }).notNull().default('Africa/Accra'),
    description: text('description'),
    logoUrl: text('logo_url'),
    phone: varchar('phone', { length: 40 }),
    email: varchar('email', { length: 254 }),
    website: varchar('website', { length: 200 }),
    addressLine1: varchar('address_line1', { length: 200 }),
    addressLine2: varchar('address_line2', { length: 200 }),
    city: varchar('city', { length: 100 }),
    region: varchar('region', { length: 100 }),
    postalCode: varchar('postal_code', { length: 30 }),
    socialLinks: jsonb('social_links').$type<Record<string, string>>(),
    employeeCount: integer('employee_count'),
    primaryGoal: varchar('primary_goal', { length: 60 }),
    goals: jsonb('goals').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    isDemo: boolean('is_demo').notNull().default(false),
    onboardedAt: timestamp('onboarded_at', { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex('businesses_slug_unique').on(t.slug)],
);

export const businessSettings = pgTable('business_settings', {
  businessId: uuid('business_id')
    .primaryKey()
    .references(() => businesses.id, { onDelete: 'cascade' }),
  taxEnabled: boolean('tax_enabled').notNull().default(false),
  taxRate: numeric('tax_rate', { precision: 5, scale: 2 }).notNull().default('0'),
  taxLabel: varchar('tax_label', { length: 40 }).notNull().default('VAT'),
  taxInclusive: boolean('tax_inclusive').notNull().default(true),
  invoicePrefix: varchar('invoice_prefix', { length: 12 }).notNull().default('INV'),
  invoiceNextNumber: integer('invoice_next_number').notNull().default(1001),
  invoiceDueDays: integer('invoice_due_days').notNull().default(14),
  invoiceNotes: text('invoice_notes'),
  invoiceFooter: text('invoice_footer'),
  orderNextNumber: integer('order_next_number').notNull().default(1001),
  lowStockThreshold: integer('low_stock_threshold').notNull().default(5),
  fiscalYearStartMonth: integer('fiscal_year_start_month').notNull().default(1),
  notificationPreferences: jsonb('notification_preferences')
    .$type<Record<string, boolean>>()
    .notNull()
    .default(sql`'{}'::jsonb`),
  enabledModules: jsonb('enabled_modules').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
  updatedAt: updatedAt(),
});

export const businessMembers = pgTable(
  'business_members',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    role: memberRoleEnum('role').notNull().default('staff'),
    title: varchar('title', { length: 80 }),
    active: boolean('active').notNull().default(true),
    invitedByUserId: uuid('invited_by_user_id'),
    invitedAt: timestamp('invited_at', { withTimezone: true }),
    joinedAt: timestamp('joined_at', { withTimezone: true }).notNull().defaultNow(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex('business_members_unique').on(t.businessId, t.userId),
    index('business_members_user_idx').on(t.userId),
  ],
);

export const subscriptions = pgTable(
  'subscriptions',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    plan: subscriptionPlanEnum('plan').notNull().default('free'),
    status: subscriptionStatusEnum('status').notNull().default('trialing'),
    seats: integer('seats').notNull().default(1),
    provider: varchar('provider', { length: 40 }),
    providerRef: varchar('provider_ref', { length: 120 }),
    trialEndsAt: timestamp('trial_ends_at', { withTimezone: true }),
    currentPeriodEnd: timestamp('current_period_end', { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex('subscriptions_business_unique').on(t.businessId)],
);

/* -------------------------------------------------------------------------- */
/* Customers                                                                   */
/* -------------------------------------------------------------------------- */

export const customers = pgTable(
  'customers',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    name: varchar('name', { length: 160 }).notNull(),
    email: varchar('email', { length: 254 }),
    phone: varchar('phone', { length: 40 }),
    company: varchar('company', { length: 160 }),
    addressLine1: varchar('address_line1', { length: 200 }),
    city: varchar('city', { length: 100 }),
    region: varchar('region', { length: 100 }),
    country: varchar('country', { length: 2 }),
    status: customerStatusEnum('status').notNull().default('active'),
    notes: text('notes'),
    source: varchar('source', { length: 80 }),
    /** Denormalised rollups, recomputed on every order/payment write. */
    totalSpentMinor: moneyCol('total_spent_minor'),
    outstandingMinor: moneyCol('outstanding_minor'),
    orderCount: integer('order_count').notNull().default(0),
    lastPurchaseAt: timestamp('last_purchase_at', { withTimezone: true }),
    createdByUserId: uuid('created_by_user_id'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index('customers_business_idx').on(t.businessId),
    index('customers_business_name_idx').on(t.businessId, t.name),
    index('customers_business_last_purchase_idx').on(t.businessId, t.lastPurchaseAt),
    uniqueIndex('customers_business_email_unique')
      .on(t.businessId, sql`lower(${t.email})`)
      .where(sql`${t.email} is not null`),
  ],
);

export const customerTags = pgTable(
  'customer_tags',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    customerId: uuid('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    tag: varchar('tag', { length: 40 }).notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex('customer_tags_unique').on(t.customerId, t.tag),
    index('customer_tags_business_tag_idx').on(t.businessId, t.tag),
  ],
);

/** Append-only timeline powering the customer profile view. */
export const customerEvents = pgTable(
  'customer_events',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    customerId: uuid('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    type: varchar('type', { length: 40 }).notNull(),
    title: varchar('title', { length: 200 }).notNull(),
    description: text('description'),
    amountMinor: bigint('amount_minor', { mode: 'number' }),
    linkId: uuid('link_id'),
    actorUserId: uuid('actor_user_id'),
    source: activitySourceEnum('source').notNull().default('user'),
    occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
    createdAt: createdAt(),
  },
  (t) => [index('customer_events_customer_idx').on(t.customerId, t.occurredAt)],
);

/* -------------------------------------------------------------------------- */
/* Catalogue & inventory                                                       */
/* -------------------------------------------------------------------------- */

export const productCategories = pgTable(
  'product_categories',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    name: varchar('name', { length: 80 }).notNull(),
    description: text('description'),
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex('product_categories_unique').on(t.businessId, sql`lower(${t.name})`)],
);

export const products = pgTable(
  'products',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    name: varchar('name', { length: 200 }).notNull(),
    kind: productKindEnum('kind').notNull().default('physical'),
    sku: varchar('sku', { length: 60 }),
    description: text('description'),
    categoryId: uuid('category_id').references(() => productCategories.id, { onDelete: 'set null' }),
    costPriceMinor: moneyCol('cost_price_minor'),
    sellingPriceMinor: moneyCol('selling_price_minor'),
    quantity: integer('quantity').notNull().default(0),
    minStock: integer('min_stock').notNull().default(0),
    trackInventory: boolean('track_inventory').notNull().default(true),
    supplier: varchar('supplier', { length: 160 }),
    durationMinutes: integer('duration_minutes'),
    active: boolean('active').notNull().default(true),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index('products_business_idx').on(t.businessId),
    index('products_business_name_idx').on(t.businessId, t.name),
    uniqueIndex('products_business_sku_unique')
      .on(t.businessId, sql`lower(${t.sku})`)
      .where(sql`${t.sku} is not null`),
  ],
);

export const inventoryMovements = pgTable(
  'inventory_movements',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    productId: uuid('product_id')
      .notNull()
      .references(() => products.id, { onDelete: 'cascade' }),
    quantityDelta: integer('quantity_delta').notNull(),
    balanceAfter: integer('balance_after').notNull(),
    reason: inventoryReasonEnum('reason').notNull().default('adjustment'),
    unitCostMinor: bigint('unit_cost_minor', { mode: 'number' }),
    note: text('note'),
    orderId: uuid('order_id'),
    actorUserId: uuid('actor_user_id'),
    source: activitySourceEnum('source').notNull().default('user'),
    createdAt: createdAt(),
  },
  (t) => [
    index('inventory_movements_product_idx').on(t.productId, t.createdAt),
    index('inventory_movements_business_idx').on(t.businessId, t.createdAt),
  ],
);

/* -------------------------------------------------------------------------- */
/* Sales                                                                       */
/* -------------------------------------------------------------------------- */

export const orders = pgTable(
  'orders',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    reference: varchar('reference', { length: 40 }).notNull(),
    customerId: uuid('customer_id').references(() => customers.id, { onDelete: 'set null' }),
    status: orderStatusEnum('status').notNull().default('confirmed'),
    paymentStatus: paymentStatusEnum('payment_status').notNull().default('unpaid'),
    subtotalMinor: moneyCol('subtotal_minor'),
    discountMinor: moneyCol('discount_minor'),
    taxMinor: moneyCol('tax_minor'),
    totalMinor: moneyCol('total_minor'),
    paidMinor: moneyCol('paid_minor'),
    costMinor: moneyCol('cost_minor'),
    channel: varchar('channel', { length: 40 }),
    note: text('note'),
    createdByUserId: uuid('created_by_user_id'),
    source: activitySourceEnum('source').notNull().default('user'),
    occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex('orders_business_reference_unique').on(t.businessId, t.reference),
    index('orders_business_occurred_idx').on(t.businessId, t.occurredAt),
    index('orders_customer_idx').on(t.customerId, t.occurredAt),
    index('orders_business_payment_status_idx').on(t.businessId, t.paymentStatus),
  ],
);

export const orderItems = pgTable(
  'order_items',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    orderId: uuid('order_id')
      .notNull()
      .references(() => orders.id, { onDelete: 'cascade' }),
    productId: uuid('product_id').references(() => products.id, { onDelete: 'set null' }),
    /** Snapshot of the product name at sale time — history must not mutate. */
    name: varchar('name', { length: 200 }).notNull(),
    quantity: integer('quantity').notNull(),
    unitPriceMinor: moneyCol('unit_price_minor'),
    unitCostMinor: moneyCol('unit_cost_minor'),
    discountMinor: moneyCol('discount_minor'),
    totalMinor: moneyCol('total_minor'),
    createdAt: createdAt(),
  },
  (t) => [index('order_items_order_idx').on(t.orderId), index('order_items_product_idx').on(t.productId)],
);

export const invoices = pgTable(
  'invoices',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    number: varchar('number', { length: 40 }).notNull(),
    customerId: uuid('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    orderId: uuid('order_id').references(() => orders.id, { onDelete: 'set null' }),
    status: invoiceStatusEnum('status').notNull().default('draft'),
    subtotalMinor: moneyCol('subtotal_minor'),
    discountMinor: moneyCol('discount_minor'),
    taxMinor: moneyCol('tax_minor'),
    totalMinor: moneyCol('total_minor'),
    paidMinor: moneyCol('paid_minor'),
    issueDate: date('issue_date').notNull(),
    dueDate: date('due_date').notNull(),
    notes: text('notes'),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    paidAt: timestamp('paid_at', { withTimezone: true }),
    createdByUserId: uuid('created_by_user_id'),
    source: activitySourceEnum('source').notNull().default('user'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex('invoices_business_number_unique').on(t.businessId, t.number),
    index('invoices_business_status_idx').on(t.businessId, t.status),
    index('invoices_customer_idx').on(t.customerId),
    index('invoices_due_date_idx').on(t.businessId, t.dueDate),
  ],
);

export const invoiceItems = pgTable(
  'invoice_items',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    invoiceId: uuid('invoice_id')
      .notNull()
      .references(() => invoices.id, { onDelete: 'cascade' }),
    productId: uuid('product_id').references(() => products.id, { onDelete: 'set null' }),
    name: varchar('name', { length: 200 }).notNull(),
    quantity: integer('quantity').notNull(),
    unitPriceMinor: moneyCol('unit_price_minor'),
    discountMinor: moneyCol('discount_minor'),
    totalMinor: moneyCol('total_minor'),
    createdAt: createdAt(),
  },
  (t) => [index('invoice_items_invoice_idx').on(t.invoiceId)],
);

export const payments = pgTable(
  'payments',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    customerId: uuid('customer_id').references(() => customers.id, { onDelete: 'set null' }),
    orderId: uuid('order_id').references(() => orders.id, { onDelete: 'cascade' }),
    invoiceId: uuid('invoice_id').references(() => invoices.id, { onDelete: 'cascade' }),
    amountMinor: moneyCol('amount_minor'),
    method: paymentMethodEnum('method').notNull().default('cash'),
    reference: varchar('reference', { length: 120 }),
    note: text('note'),
    /** Populated when the money moved through a PaymentProvider. */
    provider: varchar('provider', { length: 40 }),
    providerRef: varchar('provider_ref', { length: 160 }),
    isRefund: boolean('is_refund').notNull().default(false),
    receivedAt: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(),
    createdByUserId: uuid('created_by_user_id'),
    createdAt: createdAt(),
  },
  (t) => [
    index('payments_business_received_idx').on(t.businessId, t.receivedAt),
    index('payments_order_idx').on(t.orderId),
    index('payments_invoice_idx').on(t.invoiceId),
  ],
);

/* -------------------------------------------------------------------------- */
/* Expenses                                                                    */
/* -------------------------------------------------------------------------- */

export const expenseCategories = pgTable(
  'expense_categories',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    name: varchar('name', { length: 80 }).notNull(),
    color: varchar('color', { length: 12 }),
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex('expense_categories_unique').on(t.businessId, sql`lower(${t.name})`)],
);

export const expenses = pgTable(
  'expenses',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    categoryId: uuid('category_id').references(() => expenseCategories.id, { onDelete: 'set null' }),
    amountMinor: moneyCol('amount_minor'),
    vendor: varchar('vendor', { length: 160 }),
    description: text('description'),
    paymentMethod: paymentMethodEnum('payment_method').notNull().default('cash'),
    receiptUrl: text('receipt_url'),
    recurring: boolean('recurring').notNull().default(false),
    spentAt: timestamp('spent_at', { withTimezone: true }).notNull().defaultNow(),
    createdByUserId: uuid('created_by_user_id'),
    source: activitySourceEnum('source').notNull().default('user'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index('expenses_business_spent_idx').on(t.businessId, t.spentAt),
    index('expenses_category_idx').on(t.categoryId),
  ],
);

/* -------------------------------------------------------------------------- */
/* Work                                                                        */
/* -------------------------------------------------------------------------- */

export const tasks = pgTable(
  'tasks',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    title: varchar('title', { length: 200 }).notNull(),
    description: text('description'),
    status: taskStatusEnum('status').notNull().default('todo'),
    priority: taskPriorityEnum('priority').notNull().default('medium'),
    customerId: uuid('customer_id').references(() => customers.id, { onDelete: 'set null' }),
    orderId: uuid('order_id').references(() => orders.id, { onDelete: 'set null' }),
    invoiceId: uuid('invoice_id').references(() => invoices.id, { onDelete: 'set null' }),
    assigneeId: uuid('assignee_id').references(() => users.id, { onDelete: 'set null' }),
    dueDate: timestamp('due_date', { withTimezone: true }),
    recurrence: varchar('recurrence', { length: 20 }).notNull().default('none'),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    createdByUserId: uuid('created_by_user_id'),
    source: activitySourceEnum('source').notNull().default('user'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index('tasks_business_status_idx').on(t.businessId, t.status),
    index('tasks_business_due_idx').on(t.businessId, t.dueDate),
    index('tasks_customer_idx').on(t.customerId),
  ],
);

export const appointments = pgTable(
  'appointments',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    title: varchar('title', { length: 200 }).notNull(),
    customerId: uuid('customer_id').references(() => customers.id, { onDelete: 'set null' }),
    productId: uuid('product_id').references(() => products.id, { onDelete: 'set null' }),
    staffId: uuid('staff_id').references(() => users.id, { onDelete: 'set null' }),
    startsAt: timestamp('starts_at', { withTimezone: true }).notNull(),
    durationMinutes: integer('duration_minutes').notNull().default(60),
    status: appointmentStatusEnum('status').notNull().default('scheduled'),
    location: varchar('location', { length: 200 }),
    notes: text('notes'),
    /** Reserved for Google/Outlook sync in Phase 2. */
    externalCalendarId: varchar('external_calendar_id', { length: 200 }),
    createdByUserId: uuid('created_by_user_id'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index('appointments_business_start_idx').on(t.businessId, t.startsAt),
    index('appointments_customer_idx').on(t.customerId),
  ],
);

/* -------------------------------------------------------------------------- */
/* Signals: activity, notifications, campaigns, outbox                         */
/* -------------------------------------------------------------------------- */

export const activityEvents = pgTable(
  'activity_events',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    type: varchar('type', { length: 60 }).notNull(),
    severity: activitySeverityEnum('severity').notNull().default('info'),
    source: activitySourceEnum('source').notNull().default('system'),
    title: varchar('title', { length: 200 }).notNull(),
    description: text('description'),
    entityType: varchar('entity_type', { length: 40 }),
    entityId: uuid('entity_id'),
    actionLabel: varchar('action_label', { length: 60 }),
    actionHref: varchar('action_href', { length: 200 }),
    actorUserId: uuid('actor_user_id'),
    /** Stable key used to avoid re-emitting the same alert every scan. */
    dedupeKey: varchar('dedupe_key', { length: 160 }),
    readAt: timestamp('read_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    index('activity_events_business_created_idx').on(t.businessId, t.createdAt),
    uniqueIndex('activity_events_dedupe_unique')
      .on(t.businessId, t.dedupeKey)
      .where(sql`${t.dedupeKey} is not null`),
  ],
);

export const notifications = pgTable(
  'notifications',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    channel: notificationChannelEnum('channel').notNull().default('in_app'),
    title: varchar('title', { length: 200 }).notNull(),
    body: text('body'),
    severity: activitySeverityEnum('severity').notNull().default('info'),
    href: varchar('href', { length: 200 }),
    readAt: timestamp('read_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [index('notifications_user_idx').on(t.userId, t.createdAt)],
);

export const campaigns = pgTable(
  'campaigns',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    name: varchar('name', { length: 160 }).notNull(),
    channel: varchar('channel', { length: 20 }).notNull().default('email'),
    status: campaignStatusEnum('status').notNull().default('draft'),
    subject: varchar('subject', { length: 200 }),
    body: text('body').notNull(),
    segment: varchar('segment', { length: 60 }),
    audienceCount: integer('audience_count').notNull().default(0),
    audienceIds: jsonb('audience_ids').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    scheduledFor: timestamp('scheduled_for', { withTimezone: true }),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    createdByUserId: uuid('created_by_user_id'),
    source: activitySourceEnum('source').notNull().default('user'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('campaigns_business_idx').on(t.businessId, t.createdAt)],
);

/**
 * Every outbound message is recorded here before a channel adapter touches it.
 * In development the console adapter marks rows `simulated` — the UI shows them
 * as simulated rather than claiming a real delivery happened.
 */
export const messageOutbox = pgTable(
  'message_outbox',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    channel: varchar('channel', { length: 20 }).notNull(),
    provider: varchar('provider', { length: 40 }).notNull(),
    recipient: varchar('recipient', { length: 254 }).notNull(),
    subject: varchar('subject', { length: 200 }),
    body: text('body').notNull(),
    status: varchar('status', { length: 20 }).notNull().default('queued'),
    simulated: boolean('simulated').notNull().default(true),
    error: text('error'),
    campaignId: uuid('campaign_id').references(() => campaigns.id, { onDelete: 'set null' }),
    customerId: uuid('customer_id').references(() => customers.id, { onDelete: 'set null' }),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [index('message_outbox_business_idx').on(t.businessId, t.createdAt)],
);

/* -------------------------------------------------------------------------- */
/* AI                                                                          */
/* -------------------------------------------------------------------------- */

export const aiConversations = pgTable(
  'ai_conversations',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    title: varchar('title', { length: 200 }).notNull().default('New conversation'),
    agentId: varchar('agent_id', { length: 40 }).notNull().default('chief_of_staff'),
    archivedAt: timestamp('archived_at', { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('ai_conversations_business_user_idx').on(t.businessId, t.userId, t.updatedAt)],
);

export const aiMessages = pgTable(
  'ai_messages',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    conversationId: uuid('conversation_id')
      .notNull()
      .references(() => aiConversations.id, { onDelete: 'cascade' }),
    role: aiMessageRoleEnum('role').notNull(),
    content: text('content').notNull(),
    agentId: varchar('agent_id', { length: 40 }),
    /** Recorded tool invocations: name, arguments, duration, redacted result summary. */
    toolCalls: jsonb('tool_calls').$type<unknown[]>().notNull().default(sql`'[]'::jsonb`),
    provider: varchar('provider', { length: 20 }),
    model: varchar('model', { length: 60 }),
    inputTokens: integer('input_tokens'),
    outputTokens: integer('output_tokens'),
    latencyMs: integer('latency_ms'),
    createdAt: createdAt(),
  },
  (t) => [index('ai_messages_conversation_idx').on(t.conversationId, t.createdAt)],
);

/**
 * Consequential tool calls are never executed inline. The model proposes; a row
 * lands here in `proposed`; a human with `ai:approve_actions` decides. Execution
 * happens server-side afterwards and is recorded in ai_action_approvals + audit.
 */
export const aiActions = pgTable(
  'ai_actions',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    conversationId: uuid('conversation_id').references(() => aiConversations.id, { onDelete: 'set null' }),
    messageId: uuid('message_id').references(() => aiMessages.id, { onDelete: 'set null' }),
    requestedByUserId: uuid('requested_by_user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    agentId: varchar('agent_id', { length: 40 }).notNull().default('chief_of_staff'),
    tool: varchar('tool', { length: 60 }).notNull(),
    label: varchar('label', { length: 200 }).notNull(),
    description: text('description').notNull(),
    payload: jsonb('payload').$type<Record<string, unknown>>().notNull(),
    preview: jsonb('preview').$type<Array<{ label: string; value: string }>>().notNull().default(sql`'[]'::jsonb`),
    impact: varchar('impact', { length: 10 }).notNull().default('medium'),
    status: aiActionStatusEnum('status').notNull().default('proposed'),
    result: text('result'),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('ai_actions_business_status_idx').on(t.businessId, t.status, t.createdAt)],
);

export const aiActionApprovals = pgTable(
  'ai_action_approvals',
  {
    id: pk(),
    businessId: uuid('business_id')
      .notNull()
      .references(() => businesses.id, { onDelete: 'cascade' }),
    actionId: uuid('action_id')
      .notNull()
      .references(() => aiActions.id, { onDelete: 'cascade' }),
    decidedByUserId: uuid('decided_by_user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    decision: varchar('decision', { length: 20 }).notNull(),
    note: text('note'),
    createdAt: createdAt(),
  },
  (t) => [index('ai_action_approvals_action_idx').on(t.actionId)],
);

/* -------------------------------------------------------------------------- */
/* Audit                                                                       */
/* -------------------------------------------------------------------------- */

export const auditLogs = pgTable(
  'audit_logs',
  {
    id: pk(),
    businessId: uuid('business_id').references(() => businesses.id, { onDelete: 'cascade' }),
    actorUserId: uuid('actor_user_id').references(() => users.id, { onDelete: 'set null' }),
    actorType: activitySourceEnum('actor_type').notNull().default('user'),
    actorName: varchar('actor_name', { length: 120 }),
    action: varchar('action', { length: 80 }).notNull(),
    entityType: varchar('entity_type', { length: 40 }),
    entityId: uuid('entity_id'),
    summary: text('summary').notNull(),
    metadata: jsonb('metadata').$type<Record<string, unknown>>(),
    ipAddress: varchar('ip_address', { length: 64 }),
    userAgent: text('user_agent'),
    createdAt: createdAt(),
  },
  (t) => [
    index('audit_logs_business_created_idx').on(t.businessId, t.createdAt),
    index('audit_logs_entity_idx').on(t.entityType, t.entityId),
  ],
);

/** Product analytics — activation/engagement/retention, per business. */
export const usageEvents = pgTable(
  'usage_events',
  {
    id: pk(),
    businessId: uuid('business_id').references(() => businesses.id, { onDelete: 'cascade' }),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
    name: varchar('name', { length: 60 }).notNull(),
    properties: jsonb('properties').$type<Record<string, unknown>>(),
    createdAt: createdAt(),
  },
  (t) => [index('usage_events_name_idx').on(t.name, t.createdAt), index('usage_events_business_idx').on(t.businessId, t.createdAt)],
);

/* -------------------------------------------------------------------------- */
/* Relations (used by drizzle's relational query API)                          */
/* -------------------------------------------------------------------------- */

export const usersRelations = relations(users, ({ many }) => ({
  memberships: many(businessMembers),
  sessions: many(sessions),
}));

export const businessesRelations = relations(businesses, ({ many, one }) => ({
  members: many(businessMembers),
  customers: many(customers),
  products: many(products),
  orders: many(orders),
  invoices: many(invoices),
  expenses: many(expenses),
  settings: one(businessSettings, {
    fields: [businesses.id],
    references: [businessSettings.businessId],
  }),
}));

export const businessMembersRelations = relations(businessMembers, ({ one }) => ({
  business: one(businesses, { fields: [businessMembers.businessId], references: [businesses.id] }),
  user: one(users, { fields: [businessMembers.userId], references: [users.id] }),
}));

export const customersRelations = relations(customers, ({ many, one }) => ({
  business: one(businesses, { fields: [customers.businessId], references: [businesses.id] }),
  orders: many(orders),
  invoices: many(invoices),
  tags: many(customerTags),
  events: many(customerEvents),
}));

export const productsRelations = relations(products, ({ many, one }) => ({
  category: one(productCategories, { fields: [products.categoryId], references: [productCategories.id] }),
  movements: many(inventoryMovements),
  orderItems: many(orderItems),
}));

export const ordersRelations = relations(orders, ({ many, one }) => ({
  customer: one(customers, { fields: [orders.customerId], references: [customers.id] }),
  items: many(orderItems),
  payments: many(payments),
}));

export const orderItemsRelations = relations(orderItems, ({ one }) => ({
  order: one(orders, { fields: [orderItems.orderId], references: [orders.id] }),
  product: one(products, { fields: [orderItems.productId], references: [products.id] }),
}));

export const invoicesRelations = relations(invoices, ({ many, one }) => ({
  customer: one(customers, { fields: [invoices.customerId], references: [customers.id] }),
  items: many(invoiceItems),
  payments: many(payments),
}));

export const aiConversationsRelations = relations(aiConversations, ({ many }) => ({
  messages: many(aiMessages),
  actions: many(aiActions),
}));

export const aiActionsRelations = relations(aiActions, ({ many, one }) => ({
  conversation: one(aiConversations, { fields: [aiActions.conversationId], references: [aiConversations.id] }),
  approvals: many(aiActionApprovals),
}));

/* -------------------------------------------------------------------------- */
/* Inferred row types                                                          */
/* -------------------------------------------------------------------------- */

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Business = typeof businesses.$inferSelect;
export type BusinessSettingsRow = typeof businessSettings.$inferSelect;
export type BusinessMember = typeof businessMembers.$inferSelect;
export type Customer = typeof customers.$inferSelect;
export type NewCustomer = typeof customers.$inferInsert;
export type Product = typeof products.$inferSelect;
export type NewProduct = typeof products.$inferInsert;
export type Order = typeof orders.$inferSelect;
export type OrderItem = typeof orderItems.$inferSelect;
export type Invoice = typeof invoices.$inferSelect;
export type InvoiceItem = typeof invoiceItems.$inferSelect;
export type Payment = typeof payments.$inferSelect;
export type Expense = typeof expenses.$inferSelect;
export type Task = typeof tasks.$inferSelect;
export type Appointment = typeof appointments.$inferSelect;
export type ActivityEvent = typeof activityEvents.$inferSelect;
export type AiConversation = typeof aiConversations.$inferSelect;
export type AiMessage = typeof aiMessages.$inferSelect;
export type AiAction = typeof aiActions.$inferSelect;
export type AuditLog = typeof auditLogs.$inferSelect;
